version: '3'

services:
  mongodb:
    container_name: tennders-mongodb
    image: bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=nest
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=tennders
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379
